# Generated by Django 4.0.4 on 2022-06-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_registereditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='checkbox_10',
            field=models.CharField(default='unchecked', max_length=10),
        ),
        migrations.AddField(
            model_name='grocery',
            name='checkbox_11',
            field=models.CharField(default='unchecked', max_length=10),
        ),
        migrations.AddField(
            model_name='grocery',
            name='checkbox_12',
            field=models.CharField(default='unchecked', max_length=10),
        ),
        migrations.AddField(
            model_name='grocery',
            name='checkbox_4',
            field=models.CharField(default='unchecked', max_length=10),
        ),
        migrations.AddField(
            model_name='grocery',
            name='checkbox_5',
            field=models.CharField(default='unchecked', max_length=10),
        ),
        migrations.AddField(
            model_name='grocery',
            name='checkbox_6',
            field=models.CharField(default='unchecked', max_length=10),
        ),
        migrations.AddField(
            model_name='grocery',
            name='checkbox_7',
            field=models.CharField(default='unchecked', max_length=10),
        ),
        migrations.AddField(
            model_name='grocery',
            name='checkbox_8',
            field=models.CharField(default='unchecked', max_length=10),
        ),
        migrations.AddField(
            model_name='grocery',
            name='checkbox_9',
            field=models.CharField(default='unchecked', max_length=10),
        ),
    ]
