# Generated by Django 4.0.4 on 2022-06-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_grocery_checkbox_10_grocery_checkbox_11_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisteredItems',
        ),
    ]
