# Generated by Django 4.0.4 on 2022-06-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_delete_registereditems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='checkbox_10',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='checkbox_11',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='checkbox_12',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='checkbox_4',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='checkbox_5',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='checkbox_6',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='checkbox_7',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='checkbox_8',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='checkbox_9',
        ),
    ]
