# Generated by Django 4.0.4 on 2022-06-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0005_remove_grocery_checkbox_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='worker',
            field=models.CharField(default='頑張った人', max_length=20, verbose_name='買い物した人'),
        ),
    ]
